### ISSUE TITLE
Current active Known Issues List - A public list

### ISSUE THREAD

**Issue by mycpphurts** [mycpphurts/HorizonNPC-IssueTracker#3]
# Known issues
- ~~Logs from crafting 4 wood not being sellable.~~ Fixed at https://github.com/mycpphurts/HorizonNPCs/commit/9a556ae3da513859274584fe5bdc9b336a3775bc
- ~~Car NPC not selling cars due to an ID error~~ Fixed at https://github.com/mycpphurts/HorizonNPCs/commit/0598ba2dfa8539aeaeae34acb0b5ecb80a3e4ae5

# Planned fixes and changes
- Ability to swap old licenses to new ones with a dialogue
- ~~(Obviously) add logs to Lumberyard~~ Added in https://github.com/mycpphurts/HorizonNPCs/commit/9a556ae3da513859274584fe5bdc9b336a3775bc
- More sell options to metal at scrapyard

## If you experienced an issue, feel free to comment below.

*Note: Text like ~~this~~ means the issue is fixed*

**Comment by mycpphurts** [comment]
Issue will be closed once the updates are made and put on the *Main* server btw

**Comment by mycpphurts** [comment]
# New issues reported
- Inconsistent Mag prices on some NPCs (Thanks caverate)
- Vanilla axe doesn't chop the Frost Trees (Thanks courage)

**Will issue fixes today**

**Comment by anoxcity** [comment]
why is there not a 20rnd mag that you can buy at the NPC in the gunstore, but there is a 30rnd mag, even though 30rnd mags are illegal?

**Comment by mycpphurts** [comment]
> why is there not a 20rnd mag that you can buy at the NPC in the gunstore, but there is a 30rnd mag, even though 30rnd mags a illegal?

It's a "mimir forgor to change it" moment

Even tho the laws in-game changed to ban 30+ round mags, I forgot to swap the mag to the 20rnd one lol

Its been like that for a while but it will be changed in future commits

**Comment by mycpphurts** [comment]
Closing this since changes made on v11
