### ISSUE TITLE
cant buy aluminium still parts at the scrapyard.

### ISSUE THREAD

**Issue by anoxcity** [mycpphurts/HorizonNPC-IssueTracker#4]
currently you cant buy aluminium still parts at the scrapyard, i don't know if this was intentional or not, but i'm saying it anyways.

https://medal.tv/games/unturned/clips/1WuI0WeJt4VDL0/d1337B8xcvit?invite=cr-MSxwUmYsMTk1MjUyNTMzLA

**Comment by mycpphurts** [comment]
related to which mod so i can have a look when I can

**Comment by anoxcity** [comment]
it's the new alcohol mod that got added this wipe.

**Comment by mycpphurts** [comment]
> it's the new alcohol mod that got added this wipe.

Got it, will look into it and fix asap. I'll close this issue once fixes have been implemented in stable on git

**Comment by mycpphurts** [comment]
Closing this since changes made on v11
